### PR TITLE
Fix Django settings creation path 

### PR DESCRIPTION
**Pull request by brotich**
Fixes the invoke create setting from  `./settings.py` to `wger/settings.py`

### CODE REVIEW

**Comment by andela-brotich** [comment]
@LarryWachira this is a good update. However, could you check if the recent updates to this repo fixed the issue?

**Comment by LarryWachira** [comment]
@andela-brotich
The problem stems from the manage.py runserver command and how it works when there is no `- -setting` option. 
It looks for the settings.py in the root of the cloned folder and causes heroku deployment to fail since the settings path is `wger/settings.py`. 
I modified the default settings path in manage.py to match the new invoke path and it worked but the side effect was that it resulted in CI tests failure. 
I have had to restore the previous path because of this.

**Comment by LarryWachira** [comment]
@andela-brotich Just checked the recent updates. The changes will probably fix my earlier issue. I will test out that later.

**Comment by andela-brotich** [comment]
cool. update me on the status

**Comment by brotich** [comment]
@LarryWachira Any update on the fix to this

**Pull request closed without merging**
